### ISSUE TITLE
babel-eslint 7.x

### ISSUE THREAD

**Issue by hzoo** [babel/babel-eslint#357]
### ESLint Compat
- [x] drop node < 4 like ESLint #323
- [ ] #350 just do it now actually since it's a breaking change to change the AST output
  - [ ] Look for other places in https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/toAST.js that we can remove to have a similar AST
- [ ] https://github.com/babel/eslint-plugin-babel drop node 4 as well

### More stable library
- [ ] Less code: lets remove the flow code for unused-vars and just recommend ~~https://github.com/zertosh/eslint-plugin-flow-vars~~  [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype/issues/35). Maybe we can investigate automatically including it (but it would probably involve monkey patching which we don't want) - remove almost everything in https://github.com/babel/babel-eslint/blob/master/index.js#L128-L213
  - [ ] Bring back marking nodes as used as a seperate plugin if users want it
- [ ] figure out how to remove the scope adding/etc and do it another way

### Misc
- [ ] maybe figure out better error messages?

**Comment by danez** [comment]
👍 
We should setup the current tests to include eslint-plugin-flow-vars, so that we still se what is unsupported even when using the plugin.

**Comment by niksajanjic** [comment]
Hi, maybe this might not be the perfect place to mention this, but you guys are free to create separate issue if needed. At the moment if one would like to install this module using npm you would get deprecation warning:

npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

I'm guessing this could be solved with next version. Our team gets this warning using node 5 or 6 and npm version 3.

**Comment by hzoo** [comment]
Ok went a little crazy with what we should do, removing flow code etc since the other flow plugin rules depend on it actually. Just going to drop node 4, fix async/await so we can get a release out #361
